from specmaster.machine_learning.classic_models import SpectroRF
from specmaster.machine_learning.neural_networks import SpectroCNN
from specmaster.machine_learning.unsupervised_models import SpectroGmixture, SpectroKmeans
